modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GNU GPL v3"

[[mods]] #mandatory
modId="runic_wards" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Runic Wards" #mandatory
authors="Cyborgmas" #optional
description='''Adds the runic wards attribute, the equivalent of armor but for damage coming from magic sources.'''
[[dependencies.runic_wards]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[35.1.17,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.runic_wards]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
